### ISSUE TITLE
awx endpoint doesn't get an IP

### ISSUE THREAD

**Issue by m-shaffer** [honestica/lifen-charts#33]
Hello,

Using chart version 12.1. I am attempting to deploy the AWX chart. I am using rancher's app catalog (though I do not think that is an issue).

The deployment for awx-web applies labels

      app.kubernetes.io/instance: awx
      app.kubernetes.io/name: awx

```
# kubectl get po --show-labels | grep web
awx-web-75769fb64-vr97f    1/1     Running   1          2m32s   app.kubernetes.io/instance=awx,app.kubernetes.io/name=awx,pod-template-hash=75769fb64
```

But the service awx has selector includes:

    app.kubernetes.io/component: web
    app.kubernetes.io/instance: awx
    app.kubernetes.io/name: awx

With the difference of the component:web. As a result the endpoint doesn't get an IP:

```
# kubectl get endpoints awx
NAME   ENDPOINTS   AGE
awx    <none>      3m13s
```

If I add `app.kubernetes.io/component: web` to the deployment spec I get an endpoint IP so I believe this needs to be updated in the deployment template, but I may also be completely off base.

Thanks

**Comment by mtparet** [comment]
I opened a PR for a new version https://github.com/honestica/lifen-charts/pull/47

**Comment by mtparet** [comment]
Could you try with the new version 10.0.1 and reopen if this issue is still here ?
