### ISSUE TITLE
Instructions on installation for kube-iptables-tailer not clear

### ISSUE THREAD

**Issue by carlos-lehmann** [honestica/lifen-charts#34]
Hey @mtparet 

thanks so much for the helm chart on kube-iptables-tailer. I found it through box's issue where you left a comment with your chart. I wanted to clear some questions if you don't mind? Stuff I couldn't figure out when trying to deploy it.

in the values.yaml file you have

calico.loggingEnable
calico.apiVersion

I'm using calico as a CNI plugin but not calico network policies. Does this do anything if I set this to false, as I'm using networking.k8s.io/v1 api?

secondly on setting up iptables log prefix in the readme of the official kube-iptables-tailer of Box it's written:

"kube-iptables-tailer uses log-prefix defined in your iptables chains to parse the corresponding packet dropped logs. You can set up the log-prefix by executing the following command:"

`$ iptables -A CHAIN_NAME -j LOG --log-prefix "EXAMPLE_LOG_PREFIX: "`

Do I still have to set it? I'd guess yes. I'm checking my Kubernetes worker node with iptables -L -n | less and there's about 50+ chains in there. How do I know which chain I have to set this log-prefix? I'd like to see all packet drops of any pod in a namespace as the example shows.

Sorry if these are rather stupid questions or please let me know if I should directly engage with box for this.

Thank you,
Carlos

**Comment by mtparet** [comment]
Hello @carlos-lehmann,
Sorry for the late reply, if you are not using calico network policies (ie: `GlobalNetworkPolicy` is not avaible), you have to look at your network policies provider to add the prefix tot the dropped logs.

If your provider does not provide a way to automatically add the prefix, you have to do it manually through iptable on each node. As I use calico configuration, I do not need to manipulate manually iptables..
