### ISSUE TITLE
Looker on K8S in production and clustering

### ISSUE THREAD

**Issue by eyablonowitz** [honestica/lifen-charts#58]
This is less of an "issue" than a request for thoughts/advice:

My company is adopting Looker and must self-host it.  We'd ideally like to do it on Kubernetes if possible.  We've started playing with https://github.com/honestica/lifen-charts/tree/master/looker and https://github.com/honestica/docker-looker.

But it is not clear to me whether Kuberbetes is viable for Looker especially in production.  I am curious to hear how far the authors of this chart (e.g. @mtparet ) and other users have taken Looker on Kubernetes?  Do any do it in production?  Or is the chart just used for development purposes?

One thing I specifically noticed seems missing from the Helm chart was any support for clustering which appears to require a shared filesystem per https://docs.looker.com/setup-and-management/tutorials/clustering#required_components.  Is this something you’ve thought about adding?  We use AWS/EKS, and I was thinking of taking a stab at it using https://github.com/kubernetes-sigs/aws-efs-csi-driver.  Any thoughts or recommendations?

**Comment by mtparet** [comment]
> We'd ideally like to do it on Kubernetes if possible. 
The same for us but Google do not provide official docker/helm charts, we asked them and even proposed what we built.

> Do any do it in production? 
Yes our data team is building on it and the whole company is using it. 
If you are using it and have issues, let us know :) 

> One thing I specifically noticed seems missing from the Helm chart was any support for clustering which appears to require a shared filesystem per https://docs.looker.com/setup-and-management/tutorials/clustering#required_components. Is this something you’ve thought about adding? 

Indeed, to simplify things first we did not implement shared filesystem but it could be added in the helm chart. 
I imagine it is needed when you need lot of resources and one pod cannot be enough ? Or for availability.  Do you have another use case ?
On our side we have still lot of resources before one pod could filled a node entirely. About the availability, relaunching the pod on another node take < 1min so we do not need more availability. 

> We use AWS/EKS, and I was thinking of taking a stab at it using https://github.com/kubernetes-sigs/aws-efs-csi-driver. Any thoughts or recommendations?

We use EKS too, efs csi driver should be the good tool for that indeed.

**Comment by eyablonowitz** [comment]
Thanks @mtparet!

> I imagine it is needed when you need lot of resources and one pod cannot be enough ? Or for availability. Do you have another use case ?

> About the availability, relaunching the pod on another node take < 1min so we do not need more availability.

Yes, primarily scalability and availability.  It is true that using Kubernetes should inherently give us some availability wins even with replica-count=1.  But as you note, there would still be some expected downtime which may not be acceptable for our use case.  Scalability is probably a bigger concern if we can't horizontally scale the replica count as demand increases.  However in practice I don't yet know if/when we would need to scale beyond a single replica.

**Comment by mtparet** [comment]
>  there would still be some expected downtime which may not be acceptable for our use case.

Yes it make sense in function of the use cases. 

New versions of https://github.com/kubernetes-sigs/aws-efs-csi-driver can automatically provision efs volume it should be easier to integrate it. 
Let us know if you try to add the clustering mode to the chart, perhaps we could help.

**Comment by eyablonowitz** [comment]
>  Let us know if you try to add the clustering mode to the chart, perhaps we could help.

Will do!  We'd be happy to contribute back if we get it working.

**Comment by mtparet** [comment]
If you do not have lot of time for that, I'm wondering if the simple way is not just to do a deployment-1 and a deployment-2 and so there are no dynamic variables and you can hardcode things that need to be configured.

**Comment by eyablonowitz** [comment]
> If you do not have lot of time for that, I'm wondering if the simple way is not just to do a deployment-1 and a deployment-2 and so there are no dynamic variables and you can hardcode things that need to be configured.

Perhaps.  So it sounds like deployment-1 and deployment-2 would each have their own data filesystem (non-shared).  I'm presuming that would mean each would have independent database as well?  

I don't think I know the deployment options well enough to understand the ramifications of using multiple fully independent nodes in this way (not clustered at the DB/filesystem level).  Would these nodes be able to share Models, configuration, and other metadata?  Could these perhaps be bundled into the Docker image by a CI/CD process and hydrated via the Looker pod's API when a replica is created?

All that sounds perhaps more complex than just getting shared filesystem/db clustering working.  But it might be interesting if possible.

**Comment by mtparet** [comment]
> Perhaps. So it sounds like deployment-1 and deployment-2 would each have their own data filesystem (non-shared). I'm presuming that would mean each would have independent database as well?

I was thinking using shared data filesystem with EFS but using "static" deployment to simplify the discovery of nodes for the clustering mode.

**Comment by eyablonowitz** [comment]
Ah, sorry I misunderstood where you were going @mtparet.

There are almost certainly nuances to Looker's clustering mode that I do no not understand yet.  But in my early reading, it looks like Looker provides its own cluster node discovery mechanism with nodes registering themselves in the shared looker-database.  I'm looking at some "beta" documentation sent to us by Looker which says:

> Within a cluster, each node must be able to communicate with the other nodes. To allow this, the hostname or ip address of each node is specified in the startup configuration. When the node starts up, this value will be written into the MySQL repository. Other members of the cluster can then refer to those values to communicate with this node. To specify the hostname or ip address in the startup configuration, add `-H node1.looker.example.com` or `--hostname 123.45.6.7` to the LOOKERARGS environment variable in lookserstart.cfg.

So perhaps the chart could dynamically add that startup flag?  Something like:

values.yaml:
```
...
extraEnvs:
 - name: LOOKEREXTRAARGS
   value: --shared-storage-dir=/data/ -d /home/looker/looker-db.yml -H $(ip -4 -o addr show eth0 | awk '{print $4}' | cut -d "/" -f 1)
```

**Comment by mtparet** [comment]
You should be able also to inject the pod IP as a environment variable from the container status spec:
```
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```
              
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Comment by eyablonowitz** [comment]
Nice.  Didn't know you could do that.

So...
```
...
extraEnvs:
 - name: LOOKEREXTRAARGS
   value: --shared-storage-dir=/data/ -d /home/looker/looker-db.yml -H ${MY_POD_IP}
```

Seem like that would work and obviate the need for individual deployments (e.g. deployment-1, deployment-2 ...)?

**Comment by mtparet** [comment]
Yes !
